### ISSUE TITLE
Match bike images with reduced parametric data

### ISSUE THREAD

**Issue by lebeli** [Lyleregenwetter/BIKED#1]
Hello,

I'd like to use the bike images (folder: 'Segmented bike images/bikes/') along with some data from BIKED_reduced.csv. How can I match the images with the respective samples from the BIKED_reduced.csv? Can I match them by using the image names and the column 'Unnamed: 0' (which is some kind of index i suppose)? E.g.: 'bike (10).jpg' with data from the row where 'Unnamed: 0' is 10?. Is this assumption correct? Because there are ~250 images which names don't correspond to the values in column 'Unnamed: 0'.

I am also asking, because of your warning 'Warning: Images and processed parametric data do not contain the exact same set of models'.

Kind regards.

**Comment by Lyleregenwetter** [comment]
That's correct, The indices currently don't correspond to the parametric data. Unfortunately, I don't have the mapping from the segmented image labels to the indices. This happened due to a bit of an oversight because we generated the segmented images with a different pipeline. I'll circle back to this in a couple days and regenerate the segmented images under the same labeling scheme and update the dataset.

**Comment by lebeli** [comment]
Thank you, much appreciated!

**Comment by lebeli** [comment]
Hello @Lyleregenwetter any updates yet? 

Edit: Any chance that the processing pipelines could be released?

**Comment by Lyleregenwetter** [comment]
Yes, I have rewritten the code and am currently generating the images (approx 3000 of 4500 done). This should be finished by next week. Unfortunately I won't be able to release the pipeline at this time since an integral step is a modified version of the proprietary BikeCAD software. The best I can do is provide the code that generates the BikeCAD files from which the images are later derived.

**Comment by lebeli** [comment]
Could you give an update when the image generation is finished?

**Comment by Lyleregenwetter** [comment]
Hi @lebeli, 

Apologies for the dalay. I have updated the Dropbox with a new zip file, entitled Bikedv2. This contains svg and png files of the full bikes (all_XXXX.png) and components (component_XXXX).png. It is formatted slightly differently though. As requested, the numbers now correspond to the tabular data in BIKED (tabular data is unchanged from v1). Nonexistent components are simply included as a blank image. Any bike or component image that failed processing is omitted. 

I am hoping the new format is just as user-friendly, but I am happy to reorganize things if you'd prefer. Please let me know if I can help with anything else. Here's the link. 

https://www.dropbox.com/home/decode_lab/Datasets/Public%20Documents/BIKED%20%26%20FRAMED%20Datasets

**Comment by lebeli** [comment]
Thank you very much! In the old dataset there was a folder \Segmented bike images\bike with rectangular bike images. Any chance you have those, too? If not, how exactly did you generate these (positioning of the bike etc.)?

**Comment by Lyleregenwetter** [comment]
I did not generate these square images this time. Instead the all_XXXX bikes are the equivalent, content-wise. I believe you should be able to achieve the rectangular images through some cropping/resizing. I left them "raw" to give users more flexibility (and included the svgs in case users want to mess with the png conversion), however I am happy to do this cropping/rescaling if you'd like, since I can see that it may be convenient for people looking to quickly train CNN models. 

Some notes: 
- All bikes are aligned with the bottom left corner of the frame. 
- Depending on the dimensions of the bike, the right edge of the bike may be aligned with the right edge of the image. 
- There are some weird bikes which may be too tall to fit in the frame should you choose to align the left and right edges of the bike to the edges of a square frame

**Comment by lebeli** [comment]
Thank you very much for the insights of the process. I would appreciate it very much, if you could provide the rescaled images as well, since I can make sure that I can compare the results with the training (without labels) using your provided images.

**Comment by Lyleregenwetter** [comment]
I'm not sure how you wanted the images rescaled, but I created some square 1024x1024 images which are in the same folder. Hope this is what you needed.

**Comment by lebeli** [comment]
I noticed, that in the square images the bikes are positioned in the bottom left corner, whereas in the original dataset, the bikes are centered in the square images. Would it be possible to provide images with centered bikes?

**Comment by Lyleregenwetter** [comment]
I can artificially position the bike closer to the center, but there will be a higher chance it clips the edge of the image. I can also re-scale the images so they fit in the center, but you will lose the 1:1 correspondence from pixel distance to real-world distance. It's hard for me to guess exactly what you need for your application, so I think it may be best for you to modify the images as you see fit.

**Comment by lebeli** [comment]
So you would say for the purpose of training a CNN your given format is (best) suited? 

Edit: I would like to train a GAN with your bike images.

**Comment by Lyleregenwetter** [comment]
I see, for a GAN, It would probably be best to rescale to the size of the bike so that the bike fills up the entire image

**Comment by lebeli** [comment]
Filling up the entire image, i.e. both tires touch the side edge of the image as well as the bottom edge? And vertically the image is expanded (up) to fit a square?

**Comment by Lyleregenwetter** [comment]
I would have both tires touch the side edges, position the image at the bottom, and let it rise up a proportional distance in the image, to avoid distorting it.

**Comment by lebeli** [comment]
I have generated an example image, is that how you would do it?

![all_1058](https://user-images.githubusercontent.com/49210772/211906395-a45df016-5aa0-4b7c-8847-9509f291ab1e.png)

**Comment by Lyleregenwetter** [comment]
Yeah, I think that looks great!

**Comment by lebeli** [comment]
This issue can be closed, thank you very much for your help!

**Comment by Lyleregenwetter** [comment]
Thanks for your patience!
