### ISSUE TITLE
Dataset v2.1

### ISSUE THREAD

**Issue by lebeli** [Lyleregenwetter/BIKED#2]
Hello,

i noticed that you uploaded Biked v2.1 what exactly are the differences? And regarding to the matching of the parametric data and the images: I tried matching the images witch the column "Unnamed: 0" in the BIKED_processed.csv, but there are a lot of occurrences, where the image number does not match the index column and vice versa. Are you sure that the images and the data can be matched? If so how exactly could I do that (i.e. .loc or .iloc in pandas)?

**Comment by Lyleregenwetter** [comment]
Hi lebeli, 

Yes, the data is basically the same, I just did some reorganization. You're right that some images do not occur in the csv files and vice versa. If you specifically need bikes where both image and parametric data are available, I suggest you just drop any data for which one or the other is missing. Also, if you are already comfortable with the previous version, I see little version to switch. 

By the way, I infer from your comment about "Unnamed: 0" that you are loading the data with:

`df = pd.read_csv("csvname.csv")`

If you instead specify an index column, the indices won't be overwritten:

`df = pd.read_csv("csvname.csv", index_col=0)`

Then, to get the bike corresponding to image n, you can do:

`df.loc[n, :] `

to get the nth bike. Note that this will not be the nth index, since some bikes do not have parametric data. 

Hope this helps!
